export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";

export const GET_POST_USER_REQUEST = "GET_POST_USER_REQUEST";
export const GET_POST_USER_SUCCESS = "GET_POST_USER_SUCCESS";
export const GET_POST_USER_FAILURE = "GET_POST_USER_FAILURE";

export const GET_ALLPOST_USER_REQUEST = "GET_ALLPOST_USER_REQUEST";
export const GET_ALLPOST_USER_SUCCESS = "GET_ALLPOST_USER_SUCCESS";
export const GET_ALLPOST_USER_FAILURE = "GET_ALLPOST_USER_FAILURE";

export const GET_ALLPOSTSEARCH_USER_REQUEST = "GET_ALLPOSTSEARCH_USER_REQUEST";
export const GET_ALLPOSTSEARCH_USER_SUCCESS = "GET_ALLPOSTSEARCH_USER_SUCCESS";
export const GET_ALLPOSTSEARCH_USER_FAILURE = "GET_ALLPOSTSEARCH_USER_FAILURE";

export const DELETE_POST_USER_REQUEST = "DELETE_POST_USER_REQUEST";
export const DELETE_POST_USER_SUCCESS = "DELETE_POST_USER_SUCCESS";
export const DELETE_POST_USER_FAILURE = "DELETE_POST_USER_FAILURE";


export const SET_ALL_POST_SEARCH = "SET_ALL_POST_SEARCH";
export const SET_NOTIFICATION = "SET_NOTIFICATION";







