// Inscription
export const INSCRIPTION_REQUEST = "INSCRIPTION_REQUEST";
export const INSCRIPTION_SUCCESS = "INSCRIPTION_SUCCESS";
export const INSCRIPTION_FAILURE = "INSCRIPTION_FAILURE";

export const SET_INSCRIPTION_VALUE = "SET_INSCRIPTION_VALUE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGIN_FORGOT_REQUEST = "LOGIN_FORGOT_REQUEST";
export const LOGIN_FORGOT_SUCCESS = "LOGIN_FORGOT_SUCCESS";
export const LOGIN_FORGOT_FAILURE = "LOGIN_FORGOT_FAILURE";

export const LOGIN_OUT_USER_REQUEST = "LOGIN_OUT_USER_REQUEST";
export const LOGIN_OUT_USER_SUCCESS = "LOGIN_OUT_USER_SUCCESS";
export const LOGIN_OUT_USER_FAILURE = "LOGIN_OUT_USER_FAILURE";

export const LOGIN_GET_USER_REQUEST = "LOGIN_GET_USER_REQUEST";
export const LOGIN_GET_USER_SUCCESS = "LOGIN_GET_USER_SUCCESS";
export const LOGIN_GET_USER_FAILURE = "LOGIN_GET_USER_FAILURE";

export const LOGIN_CHECK_PWD_REQUEST = "LOGIN_CHECK_PWD_REQUEST";
export const LOGIN_CHECK_PWD_SUCCESS = "LOGIN_CHECK_PWD_SUCCESS";
export const LOGIN_CHECK_PWD_FAILURE = "LOGIN_CHECK_PWD_FAILURE";

export const LOGIN_ADD_ADMIN_REQUEST = "LOGIN_ADD_ADMIN_REQUEST";
export const LOGIN_ADD_ADMIN_SUCCESS = "LOGIN_ADD_ADMIN_SUCCESS";
export const LOGIN_ADD_ADMIN_FAILURE = "LOGIN_ADD_ADMIN_FAILURE";

export const LOGIN_CHANGE_EMAIL_REQUEST = "LOGIN_CHANGE_EMAIL_REQUEST";
export const LOGIN_CHANGE_EMAIL_SUCCESS = "LOGIN_CHANGE_EMAIL_SUCCESS";
export const LOGIN_CHANGE_EMAIL_FAILURE = "LOGIN_CHANGE_EMAIL_FAILURE";


export const SET_ERROS_MSG = "SET_ERROS_MSG";







